[tools]
"github:Canop/broot" = "latest"
"github:eza-community/eza" = "latest"
"github:jftuga/less-Windows" = "less-v685"
"github:uutils/coreutils" = "latest"
"github:uutils/diffutils" = "latest"
"github:uutils/findutils" = "latest"
bat = "latest"
difftastic = "latest"
docker-cli = "latest"
fd = "latest"
fzf = "latest"
gitui = "latest"
gopass = "latest"
helix = "latest"
lazygit = "latest"
ripgrep = "latest"
television = "latest"
usage = "latest"
yazi = "latest"
zoxide = "latest"
node = "lts"
starship = "latest"
