[metadata]
name = "pass-otp"
description = "A channel to find and select pass TOTP entry"
requirements = ["fd"]

[source]
command = "fd --type file '.gpg' ~/.password-store/totp/"
display = "{replace:s/^.*\\.password-store\\///|replace:s/\\.gpg$//}"
output = "{replace:s/^.*\\.password-store\\///|replace:s/\\.gpg$//}"

[preview]
command = "pass otp {replace:s/^.*\\.password-store\\///|replace:s/\\.gpg$//}"
