[metadata]
name = "pass"
description = "A channel to find and select pass entry"
requirements = ["fd"]

[source]
command = "fd --type file '.gpg' ~/.password-store/"
display = "{replace:s/^.*\\.password-store\\///|replace:s/\\.gpg$//}"
output = "{replace:s/^.*\\.password-store\\///|replace:s/\\.gpg$//}"

[preview]
command = "pass show {replace:s/^.*\\.password-store\\///|replace:s/\\.gpg$//}"
