[metadata]
name = "zoxide"
description = "List all matching directories"
requirements = ["zoxide", "eza"]

[source]
command = "zoxide query --list --score"
display = "{trim|split: :1..}"
output = "{trim|split: :1..}"

[preview]
command = "eza --tree {trim|split: :1..}"
